In [1]:
#Data.csv

**Step 1: Importing the libraries**

In [2]:
import pandas as pd


In [3]:
import matplotlib.pyplot as plt
import numpy as np

**Step 2: Importing dataset**

In [4]:
data=pd.read_csv('Data.csv')

**Step 3: Handling the missing data**

In [5]:
data.isnull().sum()

Country      0
Age          1
Salary       1
Purchased    0
dtype: int64

In [6]:
#handling missing data (Replacing missing data with the mean value)  
data['Age']=data['Age'].fillna(data['Age'].mean())
data['Age'].mean()

38.77777777777778

In [7]:
data['Salary']=data['Salary'].fillna(data['Salary'].mean())
data['Salary'].mean()

63777.777777777774

In [8]:
data.isnull().sum()

Country      0
Age          0
Salary       0
Purchased    0
dtype: int64

**Step 4: Encoding categorical data**

In [9]:
from sklearn.preprocessing import OneHotEncoder
x_df=pd.DataFrame(data,columns=['Country','Purchased'])
OHE=OneHotEncoder(sparse=False)
x_df=OHE.fit_transform(x_df)  

In [10]:
print(x_df)

[[1. 0. 0. 1. 0.]
 [0. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0.]
 [0. 0. 1. 1. 0.]
 [0. 1. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [0. 0. 1. 1. 0.]
 [1. 0. 0. 0. 1.]
 [0. 1. 0. 1. 0.]
 [1. 0. 0. 0. 1.]]


**Step 5: Creating a dummy variable**

In [11]:
from sklearn.preprocessing import OneHotEncoder
data1 = pd.DataFrame(data,columns=['Country'])
encoder = OneHotEncoder(drop='first', sparse=False)
# transform data
onehot = encoder.fit_transform(data1)
print(onehot)

[[0. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 0.]
 [0. 1.]
 [0. 0.]
 [1. 0.]
 [0. 0.]]


In [12]:
X=data.iloc[:,1:-1]
y=data.iloc[:,-1]

**Step 6: Splitting the datasets into training sets and Test sets**

In [13]:
from sklearn.model_selection import train_test_split  
X_train, X_test, y_train, y_test= train_test_split(X, y, test_size= 0.2, random_state=0)  

**Step 7: Feature Scaling**

In [14]:
from sklearn.preprocessing import MinMaxScaler
MMS=MinMaxScaler()
X_normalized=MMS.fit_transform(X)

In [15]:
from sklearn.preprocessing import StandardScaler  
st_x= StandardScaler()  
X_train= st_x.fit_transform(X_train)  

In [16]:
X_test= st_x.transform(X_test)  

In [17]:
X_train

array([[ 0.26306757,  0.12381479],
       [-0.25350148,  0.46175632],
       [-1.97539832, -1.53093341],
       [ 0.05261351, -1.11141978],
       [ 1.64058505,  1.7202972 ],
       [-0.0813118 , -0.16751412],
       [ 0.95182631,  0.98614835],
       [-0.59788085, -0.48214934]])

In [18]:
X_test

array([[-1.45882927, -0.90166297],
       [ 1.98496442,  2.13981082]])